[project]
name = "gym-buddy"
version = "0.1.0"
requires-python = ">=3.9,<4"
dependencies = [
  "python-telegram-bot[job-queue]==21.8",
  "python-dotenv==1.0.1",
  "psycopg[binary]==3.2.9",
  "pandas==2.2.3",
  "matplotlib==3.9.2",
  "seaborn==0.13.2",
]
